# Generated by Django 5.2.6 on 2026-02-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_userloginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='login_source',
            field=models.CharField(default='Web', max_length=50),
        ),
    ]
