# Generated by Django 6.0.2 on 2026-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
