# Generated by Django 5.2.6 on 2026-03-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_claimrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], default='student', max_length=10),
        ),
    ]
