# Generated by Django 5.2.6 on 2026-04-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_item_image_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
