# Generated by Django 5.2.6 on 2026-04-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_item_date_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ai_tags',
            field=models.TextField(blank=True, help_text='AI-extracted visual tags for matching'),
        ),
        migrations.AddField(
            model_name='item',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed'), ('archived', 'Archived')], max_length=10),
        ),
    ]
