# Generated by Django 5.2.6 on 2026-04-09 13:35

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Feedback or instructions from admin.'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Direct contact phone number.', max_length=20),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='proof_file',
            field=models.FileField(blank=True, help_text='Upload image or PDF as proof of ownership.', null=True, upload_to=items.models.get_role_upload_path),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
