# Generated by Django 5.2.6 on 2026-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_claimrequest_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location_category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location_type',
            field=models.CharField(choices=[('predefined', 'Predefined'), ('custom', 'Custom'), ('gps', 'GPS')], db_index=True, default='predefined', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
