# Generated by Django 5.2.6 on 2026-04-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_item_latitude_item_location_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
