# Generated by Django 5.2.6 on 2026-04-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_alter_item_options_alter_userloginlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='item',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved / Visible'), ('rejected', 'Rejected / Hidden')], db_index=True, default='pending', max_length=20),
        ),
    ]
