# Generated by Django 5.2.6 on 2026-04-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_remove_item_is_approved_item_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='userloginlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location_category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.DeleteModel(
            name='UserLoginLog',
        ),
    ]
