# Generated by Django 5.2.6 on 2026-04-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trust_score',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
