# Generated by Django 5.2.6 on 2026-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_userprofile_trust_score_alter_directmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', 'System Update'), ('activity', 'User Activity'), ('admin', 'Admin Alert')], db_index=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High Priority')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
