# Generated by Django 5.2.6 on 2026-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_notification_category_notification_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
