# Generated by Django 5.2.6 on 2026-04-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_directmessage_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft (Private)'), ('active', 'Active (Searchable)'), ('claimed', 'Pending Claim'), ('resolved', 'Resolved (Completed)'), ('archived', 'Archived / Retired')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='report_type',
            field=models.CharField(choices=[('lost', 'Lost Report'), ('found', 'Found Report')], db_index=True, default='found', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
