# Generated by hand for Status Data Migration

from django.db import migrations

def migrate_status_to_dimensions(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    for item in Item.objects.all():
        # Mapping Logic
        if item.status == 'lost':
            item.report_type = 'lost'
            item.lifecycle_status = 'active' if item.verification_status == 'approved' else 'draft'
        elif item.status == 'found':
            item.report_type = 'found'
            item.lifecycle_status = 'active' if item.verification_status == 'approved' else 'draft'
        elif item.status == 'claimed':
            # Historical 'claimed' items are now resolved/completed
            item.report_type = 'found' 
            item.lifecycle_status = 'resolved'
        elif item.status == 'archived':
            item.lifecycle_status = 'archived'
        
        # Security Guard: Double check the rule 'Only Approved can be Active'
        if item.lifecycle_status == 'active' and item.verification_status != 'approved':
            item.lifecycle_status = 'draft'
            
        item.save()

def reverse_migration(apps, schema_editor):
    # Mapping back logic (approximate)
    Item = apps.get_model('items', 'Item')
    for item in Item.objects.all():
        if item.lifecycle_status == 'resolved':
            item.status = 'claimed'
        elif item.lifecycle_status == 'archived':
            item.status = 'archived'
        else:
            item.status = item.report_type
        item.save()

class Migration(migrations.Migration):
    dependencies = [
        ('items', '0030_status_refactor_schema'),
    ]

    operations = [
        migrations.RunPython(migrate_status_to_dimensions, reverse_migration),
    ]
