# Generated by Django 5.2.6 on 2026-04-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_status_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_manually_verified',
            field=models.BooleanField(default=False, help_text='True if an admin manually reviewed/posted this item.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft (Private)'), ('active', 'Active (Searchable)'), ('claimed', 'Pending Claim'), ('resolved', 'Resolved (Completed)'), ('archived', 'Archived / Retired')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed'), ('archived', 'Archived')], db_index=True, max_length=10),
        ),
    ]
