# Generated by Django 5.2.6 on 2026-04-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0032_item_is_manually_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='claimed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='claimed_denominations',
            field=models.TextField(blank=True, help_text='Detail the bills/coins you lost.'),
        ),
        migrations.AddField(
            model_name='item',
            name='denominations',
            field=models.TextField(blank=True, help_text='Breakdown of bills/coins (e.g., 2x$50, 1x$20). Mandatory for found money.'),
        ),
        migrations.AddField(
            model_name='item',
            name='turnover_status',
            field=models.CharField(choices=[('pending', 'Pending turnover'), ('confirmed', 'Confirmed by Office'), ('not_required', 'Not Required')], default='not_required', max_length=20),
        ),
    ]
