# Generated by Django 5.2.6 on 2026-04-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
