# Generated by Django 5.2.6 on 2026-04-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_notification_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discovery_date',
            field=models.DateTimeField(blank=True, help_text='The actual date and time the item was lost or found.', null=True),
        ),
    ]
