# Generated by Django 5.2.6 on 2026-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_item_discovery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Amount of money if applicable', max_digits=10, null=True),
        ),
    ]
