# Generated by Django 5.2.6 on 2026-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0037_alter_item_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discovery_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The actual date and time the item was lost or found.', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed'), ('archived', 'Archived')], db_index=True, editable=False, help_text='[LEGACY] Do not use for new features.', max_length=10),
        ),
    ]
