app_name = 'items'

from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('admin/users/', views.user_directory, name='user_directory'),
    path('admin/analytics/', views.admin_analytics, name='admin_analytics'),
    path('admin/analytics/api/', views.analytics_api, name='analytics_api'),
    path('admin/logs/', views.audit_logs, name='audit_logs'),
    path('admin/trash/', views.trash_view, name='trash'),
    path('', views.item_list, name='item_list'),
    path('add/', views.report_item, name='add_item'),
    path('report/<str:status>/', views.report_item, name='report_item'),
    path('<int:pk>/', views.item_detail, name='item_detail'),
    path('edit/<int:pk>/', views.edit_item, name='edit_item'),
    path('delete/<int:pk>/', views.delete_item, name='delete_item'),
    path('renew/<int:pk>/', views.renew_item, name='renew_item'),
    path('restore/<int:pk>/', views.restore_item, name='restore_item'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('claim/<int:item_id>/', views.claim_item, name='claim_item'),
    path('admin/users/toggle-active/<int:user_id>/', views.toggle_user_active, name='toggle_user_active'),
    path('admin/users/toggle-role/<int:user_id>/', views.toggle_user_role, name='toggle_user_role'),
    path('admin/users/delete/<int:user_id>/', views.delete_user_admin, name='delete_user_admin'),
    path('admin/users/reset-password/<int:user_id>/', views.reset_user_password, name='reset_user_password'),
    path('api/notifications/', views.get_notifications, name='get_notifications'),
    path('api/notifications/read/<int:notif_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('approve/<int:item_id>/', views.approve_item, name='approve_item'),
    path('reject/<int:item_id>/', views.reject_item, name='reject_item'),
    path('claim-submit/<int:item_id>/', views.submit_claim, name='submit_claim'),
    path('claim-approve/<int:claim_id>/', views.approve_claim, name='approve_claim'),
    path('claim-reject/<int:claim_id>/', views.reject_claim, name='reject_claim'),
    path('export/csv/', views.export_csv, name='export_csv'),
    path('bulk-approve/', views.bulk_approve, name='bulk_approve'),
    path('bulk-reject/', views.bulk_reject, name='bulk_reject'),
    path('inbox/', views.inbox, name='inbox'),
    path('messages/<int:user_id>/', views.conversation, name='conversation'),
    path('api/messages/send/', views.send_message_api, name='send_message_api'),
    path('media/<path:file_path>', views.serve_private_file, name='serve_private_file'),
]
