app_name = 'items'

from django.urls import path
from . import views

urlpatterns = [
    path('my-activity/', views.my_activity, name='my_activity'),
    path('admin/users/', views.user_directory, name='user_directory'),
    path('admin/analytics/', views.admin_analytics, name='admin_analytics'),
    path('admin/trash/', views.trash_view, name='trash'),
    path('', views.item_list, name='item_list'),
    path('add/', views.report_item, name='add_item'),
    path('money-tracker/', views.money_tracker, name='money_tracker'),
    path('report/<str:status>/', views.report_item, name='report_item'),
    path('item/<int:pk>/', views.item_detail, name='item_detail'),
    path('edit/<int:pk>/', views.edit_item, name='edit_item'),
    path('delete/<int:pk>/', views.delete_item, name='delete_item'),
    path('restore/<int:pk>/', views.restore_item, name='restore_item'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('claim/<int:item_id>/', views.claim_item, name='claim_item'),
    path('admin/users/toggle-active/<int:user_id>/', views.toggle_user_active, name='toggle_user_active'),
    path('admin/users/toggle-role/<int:user_id>/', views.toggle_user_role, name='toggle_user_role'),
    path('admin/users/delete/<int:user_id>/', views.delete_user_admin, name='delete_user_admin'),
    path('admin/users/reset-password/<int:user_id>/', views.reset_user_password, name='reset_user_password'),
    path('admin/users/manage/<int:user_id>/', views.manage_user, name='manage_user'),
    path('api/notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_read'),
    path('api/notifications/mark-read/<int:pk>/', views.mark_notification_read, name='mark_read'),
    path('notifications/archive/<int:pk>/', views.archive_notification, name='archive_notification'),

    # Impressor Trio: AI, QR, PWA
    path('admin/matches/', views.match_dashboard, name='match_dashboard'),
    path('api/matches/verify/<int:suggestion_id>/', views.verify_match_api, name='verify_match_api'),
    path('api/matches/dismiss/<int:suggestion_id>/', views.dismiss_match_api, name='dismiss_match_api'),
    path('admin/scanner/', views.qr_scanner, name='qr_scanner'),
    path('api/verify-qr/', views.verify_qr_token_api, name='verify_qr_token_api'),
    path('pass/<int:claim_id>/', views.claim_pass, name='claim_pass'),

    # Messaging
    path('notifications/', views.notifications_list, name='notifications'),
    path('approve/<int:item_id>/', views.approve_item, name='approve_item'),
    path('reject/<int:item_id>/', views.reject_item, name='reject_item'),
    path('api/revert/<int:item_id>/', views.revert_item, name='revert_item'),
    path('api/smart-approve/', views.smart_approve_items, name='smart_approve_items'),
    path('claim-submit/<int:item_id>/', views.submit_claim, name='submit_claim'),
    path('claim-approve/<int:claim_id>/', views.approve_claim, name='approve_claim'),
    path('claim-reject/<int:claim_id>/', views.reject_claim, name='reject_claim'),
    path('claim-complete/<int:claim_id>/', views.complete_claim, name='complete_claim'),
    path('export/csv/', views.export_csv, name='export_csv'),
    path('export/users/csv/', views.export_users_csv, name='export_users_csv'),
    path('bulk-approve/', views.bulk_approve, name='bulk_approve'),
    path('bulk-reject/', views.bulk_reject, name='bulk_reject'),
    path('admin/claims/', views.admin_claims, name='admin_claims'),
    path('admin/trash/empty/', views.empty_trash, name='empty_trash'),
    path('admin/trash/bulk-restore/', views.bulk_restore, name='bulk_restore'),
    path('item/mark-resolved/<int:item_id>/', views.mark_item_resolved, name='mark_item_resolved'),
    path('inbox/', views.inbox, name='inbox'),
    path('messages/<int:user_id>/', views.conversation, name='conversation'),
    path('api/messages/send/', views.send_message_api, name='send_message_api'),
    path('admin/logs/', views.system_logs, name='system_logs'),
    path('admin/confirm-turnover/<int:item_id>/', views.confirm_turnover, name='confirm_turnover'),
    path('media/<path:file_path>', views.serve_private_file, name='serve_private_file'),
]
